# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 我家育儿
email: admin@wojiayuer.com
description: > # this means to ignore newlines until "baseurl:"
  科普国际权威育儿知识，坚持科学育儿，破除愚昧和偏见！
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.wojiayuer.com" # the base hostname & protocol for your site
weixin_username: wojiayuer_com
weibo_username: 我家育儿real

# Build settings
markdown: kramdown

permalink: /:title
